# /// script
# dependencies = [
# 	"mcp",
# ]
# ///

## this was generated by gemini (web) while trying to troubleshoot
## the one from local ollama gemma4

import shutil
from mcp.server.fastmcp import FastMCP

# Initialize the FastMCP server
mcp = FastMCP("Disk Usage Server")

@mcp.tool()
def get_disk_usage() -> str:
    """
    Gets disk usage information for the /System/Volumes/Data partition.
    Returns a string detailing total, used, and free gigabytes.
    """
    path = "/System/Volumes/Data"
    try:
        usage = shutil.disk_usage(path)
        
        # Convert bytes to Gigabytes (10^9)
        total_gb = round(usage.total / (10**9), 2)
        free_gb = round(usage.free / (10**9), 2)
        used_gb = round((usage.total - usage.free) / (10**9), 2)
        
        return f"Disk Usage for {path}:\nTotal: {total_gb} GB\nUsed: {used_gb} GB\nFree: {free_gb} GB"
    except Exception as e:
        return f"Failed to retrieve disk usage: {str(e)}"

if __name__ == "__main__":
    # This automatically starts the stdio server transport loop
    mcp.run()
