## generated by opencode with local ollama using gemma4
## did not work initially

import shutil
import json
from typing import Dict, Any

def get_disk_usage() -> Dict[str, float]:
    """
    Gets disk usage information for the /Systems/Volumes/Data partition.
    Returns a dictionary with total_gb, used_gb, and free_gb.
    """
    path = "/System/Volumes/Data"
    try:
        # Get usage statistics in bytes
        usage = shutil.disk_usage(path)
        
        # Convert bytes to Gigabytes (10^9)
        total_bytes = usage.total
        free_bytes = usage.free
        used_bytes = total_bytes - free_bytes
        
        return {
            "total_gb": round(total_bytes / (10**9), 2),
            "used_gb": round(used_bytes / (10**9), 2),
            "free_gb": round(free_bytes / (10**9), 2)
        }
    except Exception as e:
        # Basic error handling
        return {"error": f"Failed to retrieve disk usage: {str(e)}"}

if __name__ == "__main__":
    # This provides the functionality for a tool named get_disk_usage
    print(json.dumps(get_disk_usage()))
